In [2]:
import numpy as np
zDA = 30
iDA = 84
jDA = 96
D = np.zeros((iDA,jDA,zDA))
C_down = np.zeros((iDA,jDA,zDA))

delta_OBS = H\*F\*delta_z-delta_y  
R_formula 暂时认为是对角线矩阵  
R_inverse 就只需要写成一个常量->之后可能根据卫星的实际值来修改  
则下面写的是delta_OBS^T \* R_inverse \* delta_OBS

In [4]:
p_OBS = 40000 # p_OBS 需要根据卫星的观测数目来读
delta_OBS = np.array((p_OBS,1))# 应该是用前期程序计算出来的
R_inverse = np.full((p_OBS,1),1/77) #1/77是我随意设置的

In [ ]:
def func_square_delta_OBS(delta_OBS,R_inverse):
    sum_delta_OBS = 0
    for i in range(p_OBS):
        sum_delta_OBS = sum_delta_OBS + R_inverse[p_OBS][0]*delta_OBS[p_OBS][0]**2
return sum_delta_OBS

下面写的是H、F变到公式里实际运算的过程

In [5]:
# H_formula = np.zeros((p_OBS,iDA*jDA*zDA))
H = []
for p in range(p_OBS):
    H_each = np.zeros((iDA,jDA,zDA))
    H.append(H_each)

In [ ]:
def func_delta_OBS(H,F,delta_z,delta_y):
    
    delta

In [ ]:
def func_delta_y(x_b,y,H):
    delta_y = np.zeros((p_OBS,1))
    for p in range(pOBS):
        for z in range(zDA):
            for i in range(iDA):
                for j in range(jDA):
                    delta_y[p][0] = delta_y[p][0] + y[p][0] - H[z][p][i][j]*x_b[i][j][z][0]
        #delta_y = y-H*x_b
    return delta_y

# 测试数据

In [24]:
import random
import numpy as np

x_b = np.zeros((2,3,2))
for i in range(2):
    for j in range(3):
        for z in range(2):
            x_b[i][j][z]=random.randint(1,9)
print(x_b)

y = np.zeros((2,1))
for p in range(2):
    y[p][0]=random.randint(1,9)
print(y)

H = []
for p in range(2): # 2个观测
    H_each = np.zeros((2,3,2)) # 2行，3列,2层
    
    for z in range(2):
        for j in range(3):
            for i in range(2):
                H_each[i][j][z]=random.randint(1,9)
    
    H.append(H_each)
print(H)

[[[7. 3.]
  [1. 6.]
  [9. 5.]]

 [[1. 9.]
  [7. 8.]
  [5. 8.]]]
[[6.]
 [3.]]
[array([[[8., 8.],
        [5., 8.],
        [7., 3.]],

       [[8., 4.],
        [2., 5.],
        [5., 7.]]]), array([[[9., 5.],
        [3., 8.],
        [2., 1.]],

       [[2., 3.],
        [6., 7.],
        [8., 2.]]])]


In [38]:
H = []
H_each = np.zeros((2,3,2)) # 2行，3列,2层
H_each[1][1][0] = 4
H_each[1][1][1] = 1
H.append(H_each)
H_each = np.zeros((2,3,2)) # 2行，3列,2层
H_each[0][2][0] = 3
H_each[0][2][1] = 2
H.append(H_each)
print(H)

[array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [4., 1.],
        [0., 0.]]]), array([[[0., 0.],
        [0., 0.],
        [3., 2.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])]


In [44]:
def func_delta_y(x_b,y,H):
    delta_y = np.zeros((2,1))
    Hx_b = np.zeros((2,1))
    for p in range(2):
        for z in range(2):
            for j in range(3):
                for i in range(2):
                    #print(delta_y[p][0],Hx_b[p][0],y[p][0], H[p][z][j][i],x_b[i][j][z])
                    Hx_b[p][0] = Hx_b[p][0] + H[p][z][j][i]*x_b[i][j][z]
                    delta_y[p][0] = y[p][0]-Hx_b[p][0]
        #delta_y = y-H*x_b
    return delta_y
func_delta_y(x_b,y,H)

0.0 0.0 6.0 0.0 7.0
6.0 0.0 6.0 0.0 1.0
6.0 0.0 6.0 0.0 1.0
6.0 0.0 6.0 0.0 7.0
6.0 0.0 6.0 0.0 9.0
6.0 0.0 6.0 0.0 5.0
6.0 0.0 6.0 0.0 3.0
6.0 0.0 6.0 0.0 9.0
6.0 0.0 6.0 4.0 6.0
-18.0 24.0 6.0 1.0 8.0
-26.0 32.0 6.0 0.0 5.0
-26.0 32.0 6.0 0.0 8.0
0.0 0.0 3.0 0.0 7.0
3.0 0.0 3.0 0.0 1.0
3.0 0.0 3.0 0.0 1.0
3.0 0.0 3.0 0.0 7.0
3.0 0.0 3.0 3.0 9.0
-24.0 27.0 3.0 2.0 5.0
-34.0 37.0 3.0 0.0 3.0
-34.0 37.0 3.0 0.0 9.0
-34.0 37.0 3.0 0.0 6.0
-34.0 37.0 3.0 0.0 8.0
-34.0 37.0 3.0 0.0 5.0
-34.0 37.0 3.0 0.0 8.0


array([[-26.],
       [-34.]])